{ config, pkgs, lib, noctalia, ... }:

{
  imports = [
    noctalia.homeModules.default
  ];

  programs.noctalia-shell = {
    enable = true;
    # noctalia.json file is autogenerated by noctalia shell in settings>general>copy settings
    settings = builtins.fromJSON (builtins.readFile ./noctalia.json);
  };
}
